name: Create a release

on:

  # Runs on tag creation
  push:
    tags:
      - '*'

jobs:

  # Build the app artifact
  build-and-release:
    name: Build the app and create a release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build the app
        run: |
          cd klupa-backend
          mvn package

      - name: Create a release
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}

      - name: Upload asset
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: './klupa-backend/target/klupa-backend-0.0.1-SNAPSHOT.jar'
          asset_name: backend.jar
          asset_content_type: application/java-archive
